In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("covid_toy.csv")
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [3]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

In [4]:
X_train, X_test, y_train, y_test = train_test_split(df[["age", "gender", "fever", "cough", "city"]], df["has_covid"], train_size=0.8, random_state=0)

In [5]:
simple_imputer = SimpleImputer()    # handles missing values - Fills in missing data in your dataset
ohe = OneHotEncoder()       # Converts categories into binary columns
oe = OrdinalEncoder()       # Converts categories into numbers

In [6]:
# Creating a single transformer that will apply different preprocessing steps to different columns all at once.
# SimpleImputer --> Fills any missing value with the mean of the column
# OrdinalEncoder --> Converts Mild --> 0, Strong --> 1
# OHE --> Returns a regular numpy array instead of a sparse matrix
transformer = ColumnTransformer(transformers=[
    ("tnf1", SimpleImputer(), ["fever"]),
    ("tnf2", OrdinalEncoder(categories=[["Mild", "Strong"]]), ["cough"]),
    ("tnf3", OneHotEncoder(sparse_output=False, drop="first"), ["gender", "city"])
], remainder="passthrough")

In [7]:
# Applying all those transformations I defined and converting the result into a pandas dataframe
# fit() --> The transformer learns the necessary stats from the data. SimpleImputer calculates the mean of the fever column.
#   OrdinalEncoder learns the mapping Mild --> 0, Strong --> 1
#   OHE learns all the unique categories in the gender and city columns

# transform() --> Applies the learned transformation to your data
# fit_transform() --> Does both step at once
# Result --> A numpy array with all transformations applied
transformed = transformer.fit_transform(df)
transformed

array([[103.0, 0.0, 1.0, 0.0, 1.0, 0.0, 60, 'No'],
       [100.0, 0.0, 1.0, 1.0, 0.0, 0.0, 27, 'Yes'],
       [101.0, 0.0, 1.0, 1.0, 0.0, 0.0, 42, 'No'],
       [98.0, 0.0, 0.0, 0.0, 1.0, 0.0, 31, 'No'],
       [101.0, 0.0, 0.0, 0.0, 0.0, 1.0, 65, 'No'],
       [100.84444444444445, 0.0, 0.0, 0.0, 0.0, 0.0, 84, 'Yes'],
       [101.0, 1.0, 1.0, 0.0, 0.0, 0.0, 14, 'No'],
       [100.84444444444445, 1.0, 0.0, 0.0, 0.0, 1.0, 20, 'Yes'],
       [100.0, 1.0, 0.0, 0.0, 0.0, 0.0, 19, 'No'],
       [101.0, 0.0, 0.0, 1.0, 0.0, 0.0, 64, 'No'],
       [100.84444444444445, 0.0, 0.0, 1.0, 0.0, 0.0, 75, 'No'],
       [98.0, 0.0, 0.0, 0.0, 0.0, 1.0, 65, 'Yes'],
       [99.0, 1.0, 0.0, 0.0, 1.0, 0.0, 25, 'No'],
       [102.0, 0.0, 1.0, 0.0, 0.0, 0.0, 64, 'Yes'],
       [104.0, 0.0, 1.0, 0.0, 0.0, 0.0, 51, 'No'],
       [103.0, 1.0, 1.0, 0.0, 1.0, 0.0, 70, 'Yes'],
       [103.0, 0.0, 0.0, 0.0, 1.0, 0.0, 69, 'Yes'],
       [98.0, 1.0, 0.0, 1.0, 0.0, 0.0, 40, 'No'],
       [98.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6

In [8]:
# Converts the numpy array back into the pandas dataframe
transformed = pd.DataFrame(transformed)
transformed

,0,1,2,3,4,5,6,7
0,103.0,0.0,1.0,0.0,1.0,0.0,60,No
1,100.0,0.0,1.0,1.0,0.0,0.0,27,Yes
2,101.0,0.0,1.0,1.0,0.0,0.0,42,No
3,98.0,0.0,0.0,0.0,1.0,0.0,31,No
4,101.0,0.0,0.0,0.0,0.0,1.0,65,No
...,...,...,...,...,...,...,...,...
95,104.0,0.0,0.0,0.0,0.0,0.0,12,No
96,101.0,1.0,0.0,0.0,1.0,0.0,51,Yes
97,101.0,0.0,0.0,0.0,0.0,0.0,20,No
98,98.0,1.0,0.0,0.0,0.0,1.0,5,No


In [9]:
# Fitting and transforming only on the training data
# .fit() --> Learning phase
# .transform() --> Application Phase
X_train_transformed = transformer.fit_transform(X_train)
X_train_transformed

array([[ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  22.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  31.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  72.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  66.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  14.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  10.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          1.    

In [10]:
# Transforming the test data using parameters learned from the training data (using stats and mapping learned from X_train)
# SimpleImputer on fever --> Uses the mean calculated from X_train
# OrdinalEncoder on cough --> Uses the mapping learned from X_train
# OHE on gender and city --> Creates the exact same columns as it did for X_train
X_test_transformed = transformer.transform(X_test)
X_test_transformed

array([[100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  19.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  25.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  42.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  27.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  69.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.    

# GPT Code

In [11]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Sample dataset
df = pd.DataFrame({
    'age': [25, 32, 47],
    'salary': [50000, 60000, 120000],
    'city': ['New York', 'Paris', 'Tokyo']
})

# Define transformations
ct = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['age', 'salary']),
        ('cat', OneHotEncoder(), ['city'])
    ],
    remainder='drop')

# Fit and transform
X_transformed = ct.fit_transform(df)

print("Transformed Array:\n", X_transformed)
print("Feature Names:\n", ct.get_feature_names_out())

Transformed Array:
 [[-1.05332743 -0.86266219  1.          0.          0.        ]
 [-0.29057308 -0.53916387  0.          1.          0.        ]
 [ 1.34390052  1.40182605  0.          0.          1.        ]]
Feature Names:
 ['num__age' 'num__salary' 'cat__city_New York' 'cat__city_Paris'
 'cat__city_Tokyo']
