In [1]:
import numpy as np
import pandas as pd

# 0-Tensor

In [2]:
a = np.array(3)
print(a)
print(a.ndim)

3
0


# 1-Tensor

In [3]:
b = np.array([1, 2, 3])
print(b)
print(b.ndim)

[1 2 3]
1


# 2-Tensor

In [4]:
c = np.array([[4, 6, 7], [-7, -10, 20]])
print(c)
print(c.ndim)

[[  4   6   7]
 [ -7 -10  20]]
2
