In [1]:
import pandas as pd
df = pd.read_csv("diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [2]:
# Split the data into X and y
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [4]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [5]:
# This returns the predicted probabilities for each class for all samples in X_test.
# For binary classification, it returns a 2D array.
# Each row contains two probabilities: prob of class 0, prob of class 1
y_scores = model.predict_proba(X_test)[:, 1]

In [6]:
# ROC curve needs probability scores because they evaluate the models performance across all possible classification thresholds. By having the probability that each sample belongs to the positive class, you can see how well the model discriminates between the two classes at different threshold values.
y_scores

array([0.9598824 , 0.16518942, 0.09467776, 0.63345122, 0.12291357,
       0.03809495, 0.7412436 , 0.84725609, 0.3756741 , 0.3674447 ,
       0.56993274, 0.95938494, 0.28559975, 0.16999879, 0.12298158,
       0.16032431, 0.86300245, 0.02700695, 0.42821537, 0.25393619,
       0.66531914, 0.42139585, 0.22253946, 0.06508523, 0.05057629,
       0.36537902, 0.04558306, 0.90716492, 0.11377492, 0.14423284,
       0.45981835, 0.25352477, 0.09405934, 0.45765006, 0.10221368,
       0.71908412, 0.45566388, 0.08602998, 0.34160517, 0.74792315,
       0.28323527, 0.21870604, 0.1603078 , 0.83283712, 0.74367945,
       0.00869392, 0.08684144, 0.20510351, 0.35488691, 0.30219663,
       0.4067936 , 0.19190882, 0.87382495, 0.49771371, 0.13821808,
       0.00272793, 0.06243482, 0.55869006, 0.27871671, 0.07332729,
       0.72497443, 0.46592669, 0.11000989, 0.72500438, 0.6927929 ,
       0.90504671, 0.72070111, 0.1435236 , 0.36251446, 0.11070165,
       0.12646668, 0.41123848, 0.10134418, 0.95136048, 0.85304

## ROC Computation -- This is only for binary classification

In [7]:
# Import the ROC curve function from sklearn
from sklearn.metrics import roc_curve
# y-test --> The true labels
# y_scores --> the predicted probabilities (not class predictions)
# thresholds --> Decision thresholds used to compute FPR and TPR. The model is compared to each threshold, if score >= threshold, predict 1.....otherwise predict 0

# This function calculates the ROC curve by computing the fpr, tpr at various threshold values
fpr, tpr, thresholds = roc_curve(y_test, y_scores)

In [13]:
fpr

array([0.        , 0.        , 0.        , 0.01869159, 0.01869159,
       0.02803738, 0.02803738, 0.05607477, 0.05607477, 0.06542056,
       0.06542056, 0.07476636, 0.07476636, 0.14018692, 0.14018692,
       0.1588785 , 0.1588785 , 0.17757009, 0.17757009, 0.18691589,
       0.18691589, 0.26168224, 0.26168224, 0.30841121, 0.30841121,
       0.3271028 , 0.3271028 , 0.34579439, 0.34579439, 0.37383178,
       0.37383178, 0.44859813, 0.44859813, 0.48598131, 0.48598131,
       0.8411215 , 0.8411215 , 1.        ])

In [14]:
tpr

array([0.        , 0.0212766 , 0.04255319, 0.04255319, 0.25531915,
       0.25531915, 0.46808511, 0.46808511, 0.5106383 , 0.5106383 ,
       0.59574468, 0.59574468, 0.61702128, 0.61702128, 0.63829787,
       0.63829787, 0.68085106, 0.68085106, 0.72340426, 0.72340426,
       0.74468085, 0.74468085, 0.82978723, 0.82978723, 0.87234043,
       0.87234043, 0.89361702, 0.89361702, 0.91489362, 0.91489362,
       0.93617021, 0.93617021, 0.95744681, 0.95744681, 0.9787234 ,
       0.9787234 , 1.        , 1.        ])

In [8]:
# Threshold contains all unique score values from y_scores, sorted from highest to lowest, plus an initial inf
thresholds

array([       inf, 0.9598824 , 0.95938494, 0.90716492, 0.74873057,
       0.74792315, 0.66223399, 0.63852123, 0.62453995, 0.62453941,
       0.55869006, 0.54131465, 0.52689356, 0.45717003, 0.45566388,
       0.42375744, 0.42139585, 0.4067936 , 0.39686351, 0.39377665,
       0.38993648, 0.36251446, 0.34871447, 0.31038837, 0.30219663,
       0.29480412, 0.2901388 , 0.28323527, 0.27871671, 0.25352477,
       0.24737967, 0.20656515, 0.20510351, 0.19190882, 0.18985253,
       0.07349036, 0.07332729, 0.00272793])

In [9]:
import plotly.graph_objects as go
import numpy as np

# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name='ROC curve'
)

# Only label every nth point to avoid cluttering
n = 10
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices],
    y=tpr[indices],
    mode='markers+text',
    name='Threshold points',
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]],
    textposition='top center')

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash'))

data = [trace0, trace1, trace2]
# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=False)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)
# Show figure
fig.show()

In [10]:
# Assume that fpr, tpr, thresholds have already been calculated
optimal_idx = np.argmax(tpr-fpr)
optimal_threshold = thresholds[optimal_idx]
print("Optimal Threshold is:", optimal_threshold)

Optimal Threshold is: 0.27871671494673017


In [11]:
import plotly.graph_objects as go
import numpy as np
from sklearn.metrics import roc_auc_score

# Assuming fpr, tpr, thresholds are already calculated as before
fpr, tpr, thresholds = roc_curve(y_test, y_scores)
# Calculate the AUC (Area Under the Curve)
roc_auc = roc_auc_score(y_test, y_scores)

# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name=f'ROC curve (Area = {roc_auc:.2f})')

# Only label every nth point to avoid cluttering
n = 10
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices],
    y=tpr[indices],
    mode='markers+text',
    name='Threshold points',
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]],
    textposition='top center')

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash'))

data = [trace0, trace1, trace2]
# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=True)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)
# Show figure
fig.show()


In [12]:
import numpy as np
import plotly.graph_objects as go
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import StandardScaler

# Assuming that X_train, X_test, y_train, y_test are already defined

# SVM requires feature scaling for better performance
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic Regression model
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)
lr_scores = lr_model.predict_proba(X_test)[:,1]

# SVM model
svm_model = SVC(probability=True)
svm_model.fit(X_train_scaled, y_train)
svm_scores = svm_model.predict_proba(X_test_scaled)[:,1]

# Generate ROC curve data for logistic regression model
lr_fpr, lr_tpr, lr_thresholds = roc_curve(y_test, lr_scores)
lr_auc = roc_auc_score(y_test, lr_scores)

# Generate ROC curve data for SVM model
svm_fpr, svm_tpr, svm_thresholds = roc_curve(y_test, svm_scores)
svm_auc = roc_auc_score(y_test, svm_scores)

# Generate a trace for the Logistic Regression ROC curve
trace0 = go.Scatter(
    x=lr_fpr,
    y=lr_tpr,
    mode='lines',
    name=f'Logistic Regression (Area = {lr_auc:.2f})'
)

# Generate a trace for the SVM ROC curve
trace1 = go.Scatter(
    x=svm_fpr,
    y=svm_tpr,
    mode='lines',
    name=f'SVM (Area = {svm_auc:.2f})'
)

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=True
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()
