In [1]:
import numpy as np

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Comparisons

In [7]:
# < (less than)
print(x<5)

[ True  True  True  True  True False False False False False]


In [8]:
# > (Greater than)
print(x>4)

[False False False False False  True  True  True  True  True]


In [10]:
# <= (less than equal to)
print(x<=5)

[ True  True  True  True  True  True False False False False]


In [11]:
# >= (greater than equal to)
print(x>=5)

[False False False False False  True  True  True  True  True]


In [12]:
# != (not equal)
print(x!=2)

[ True  True False  True  True  True  True  True  True  True]


In [13]:
# == (equal)
print(x==4)

[False False False False  True False False False False False]


## Working with Boolean Arrays

In [14]:
x = np.array([[5, 0, 3, 3],
              [7, 9, 3, 5],
              [2, 4, 7, 6]])

In [18]:
# Count the number of True entries
print(np.count_nonzero(x<6))
print(np.sum(x<6, axis=1))

8
[4 2 2]


In [19]:
print(np.any(x>8))  # Any value > 8
print(np.any(x<0))  # Any value < 0
print(np.all(x<10)) # Are all values < 10
print(np.all(x==10))    # Are all values equal to 10

True
False
True
False


# Boolean Arrays as Masks

In [20]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [21]:
x[x<5]

array([0, 3, 3, 3, 2, 4])