In [1]:
import numpy as np

# Array Creation

In [2]:
# np.array() - Create an array from list or tuples
a = np.array([1, 2, 3])
print(f"Creating a simple array: {a}")

# np.zeros() - Create an array filled with zeros
b = np.zeros((4, 3))
print(f"Zeros: {b}")

# np.ones() - Create an array filled with ones
c = np.ones((4, 3))
print(f"Ones: {c}")

# np.eye() - Identity matrix
d = np.eye(5)
print(f"Identity Matrix: {d}")

# np.arange() - Create an array with evenly spaced values
e = np.arange(1, 51, 3)
print(f"Arange: {e}")

# np.linspace() - Create an array with linearly spaced values
f = np.linspace(1, 100, 25)
print(f"Linspace: {f}")

# np.random.rand() - Random numbers in [0, 1), Uniform
g = np.random.rand(2, 2)
print(f"Random.rand {g}")

# np.random.randn() - Random numbers, standard Normal Distribution
h = np.random.randn(2, 2)
print(f"Random.randn: {h}")

# np.random.randint() - Random numbers in a given Range
i = np.random.randint(1, 10, (2, 2))
print(f"Random.randint: {i}")

Creating a simple array: [1 2 3]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Arange: [ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
Linspace: [  1.      5.125   9.25   13.375  17.5    21.625  25.75   29.875  34.
  38.125  42.25   46.375  50.5    54.625  58.75   62.875  67.     71.125
  75.25   79.375  83.5    87.625  91.75   95.875 100.   ]
Random.rand [[0.26702037 0.45657015]
 [0.79223755 0.23460162]]
Random.randn: [[-0.96259729 -0.17213689]
 [-0.91652778  0.120749  ]]
Random.randint: [[8 9]
 [8 8]]


# Array Operations

In [9]:
x = np.array([[1, 2], [3, 4]])
print(x)

# nd.shape - Returns the dimensions
print(f"Shape: {x.shape}")

# np.ndim - Number of dimensions
print(f"Ndim: {x.ndim}")

# nd.size - Total number of elements
print(f"Size: {x.size}")

# nd.dtype - Data type of elements
print(f"Data Type: {x.dtype}")

# nd.reshape() - Reshape array without changing data
print(f"Reshaped array: {x.reshape((4, 1))}")

# np.flatten() - Flatten a multi-dimensional array
print(f"Flattening of array: {x.flatten()}")

# np.transpose() - Transpose of array
print(f"Transpose: {x.transpose()}")

# np.concatenate() - Concatenate arrays
# print(f"Concatenation: {np.concatenate((x, a), axis = 0)}")

# np.vstack / np.hstack() - Stack vertically/horizontally

[[1 2]
 [3 4]]
Shape: (2, 2)
Ndim: 2
Size: 4
Data Type: int64
Reshaped array: [[1]
 [2]
 [3]
 [4]]
Flattening of array: [1 2 3 4]
Transpose: [[1 3]
 [2 4]]


# Math Operations

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# np.add - Element wise addition
print(f"Element-wise addition: {np.add(a, b)}")

# np.subtract - Element wise subtraction
print(f"Element-wise subtraction: {np.subtract(a, b)}")

# np.multiply() - Element eise multiplication
print(f"Element wise multiplication: {np.multiply(a, b)}")

# np.dot() - Matrix multplication
print(f"Matrix Multiplication: {np.dot(a, b)}")

# np.divide() - element wise division
print(f"Element wise division: {np.divide(b, a)}")

# np.exp() - Exponential Function
print(f"Exponential: {np.exp(a)}")

# np.log() - Logarithmic Function
print(f"Log: {np.log(a)}")

# np.sqrt() - Square Root function
print(f"Square Root: {np.sqrt(a)}")

# np.power() - Raise elements to a power
print(f"Power: {np.power(a, 2)}")

Element-wise addition: [5 7 9]
Element-wise subtraction: [-3 -3 -3]
Element wise multiplication: [ 4 10 18]
Matrix Multiplication: 32
Element wise division: [4.  2.5 2. ]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Log: [0.         0.69314718 1.09861229]
Square Root: [1.         1.41421356 1.73205081]
Power: [1 4 9]


# Statistical Functions

In [5]:
a = np.array([1,2,3,4,5])

# np.mean() - Mean of elements
print(f"Mean: {np.mean(a)}")

# np.median() - Median value
print(f"Median: {np.median(a)}")

# np.std() - Standard Deviation
print(f"Standard Deviation: {np.std(a)}")

# np.var() - Variance
print(f"Variance: {np.var(a)}")

# np.sum() - Sum of elements
print(f"Sum: {np.sum(a)}")

# np.min() - Minimum
print(f"Minimum: {np.min(a)}")

# np.max() - Maximum
print(f"Maximum: {np.max(a)}")

# np.argmin() - Index of minimum value
print(f"Argmin: {np.argmin(a)}")

# np.argmax() - Index of maximum value
print(f"Argmax: {np.argmax(a)}")

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
Sum: 15
Minimum: 1
Maximum: 5
Argmin: 0
Argmax: 4


# Indexing and Slicing

In [6]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr, end="\n\n")

# Indexing - arr[i]
print("Indexing:", arr[0, 1])  # 20

# Slicing - arr[i:j]
print("Slicing:", arr[:, 1])  # [20, 50]

# Boolean Indexing - arr[a > 0]
print("Boolean Indexing:", arr[arr > 35])

# Fancy Indexing - arr[[1, 2, 3]]
print("Fancy Indexing:", arr[[0, 1], [1, 2]])  # [20, 60]

[[10 20 30]
 [40 50 60]]

Indexing: 20
Slicing: [20 50]
Boolean Indexing: [40 50 60]
Fancy Indexing: [20 60]


# Cleaning / Handling Missing Values

In [7]:
arr = np.array([1, np.nan, 3, np.nan, 5])
print(arr, end="\n\n")

# np.isnan()
print(np.isnan(arr))

# np.isfinite()
print(np.isfinite(arr))

# np.nanmean()
print(np.nanmean(arr))

# np.nansum()
print(np.nansum(arr))

[ 1. nan  3. nan  5.]

[False  True False  True False]
[ True False  True False  True]
3.0
9.0


# Utility Functions

In [8]:
a = np.array([3, 1, 2, 3, 4])

# np.unique() - Get the unique values in an array
print(np.unique(a))

# np.sort() - Returns a sorted copy of an array. Does not change the original array.
print(np.sort(a))

# np.where() - Perform element-wise selection based on a condition.
result = np.where(a > 2, 100, a)  # If an element in a is > 2 replace it with 100, else keep it as-is.
print(result)

# np.clip() - Limit values in an array to a specified range.
clipped = np.clip(a, 2, 3)  # All values <2 become 2, all >3 become 3.
print(clipped)

# np.any() - Check boolean conditions across an array.
print(np.any(a>2))

# np.all()
print(np.all(a>2))

[1 2 3 4]
[1 2 3 3 4]
[100   1   2 100 100]
[3 2 2 3 3]
True
False


# Reshaping of Arrays

In [12]:
# Reshape method
x = np.arange(1, 11).reshape((5, 2))
print(x)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


# Concatenation of arrays

In [20]:
# np.concatenate
# Syntax --> np.concatenate((array1, array2, ...), axis=0, out=None, dtype=None)
# Concatenating 1-D array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concatenate((arr1, arr2), axis=0)
print(arr1)
print(arr2)
print("After concatenation:")
print(result)

[1 2 3]
[4 5 6]
After concatenation:
[1 2 3 4 5 6]


In [25]:
# Concatenating 2-D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
vertical_result = np.concatenate((a, b), axis=0)
horizontal_result = np.concatenate((a, b), axis=1)
print(a)
print(b)
print("Vertical Concatenation:")
print(vertical_result)
print("Horizontal Concatenation:")
print(horizontal_result)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Vertical Concatenation:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Concatenation:
[[1 2 5 6]
 [3 4 7 8]]


In [26]:
# hstack / vstack

# Splitting of Arrays

In [27]:
# np.split
# Syntax --> numpy.split(array, indices_or_sections, axis=0)

# array --> The input array to be divided

# indices_or_sections --> How the array is split. If an integer N, then the array is divided into N equal parts along the specified
# axis. A valueError is raised if it cannot be equally divided. If a 1-D array (list or tuple) of sorted integers, the entries indicate the indices where the array is split.

# axis: The axis along which to split the array. It defaults to 0 (row-wise in 2D arrays, or the first dimension)

x = np.arange(9)
result = np.split(x, 3)     # Split x into 3 equal parts
print(result)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
