In [1]:
import numpy as np

## ufuncs applied on 1-D array

In [2]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

## ufuncs applied on 2-D array

In [3]:
x = np.arange(9).reshape((3, 3))
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

# Array Arithmetic

In [9]:
x = np.arange(4)
print(f"x: {x}")
print(f"x-5: {x-5}")       # Subtraction
print(f"x+5: {x+5}")       # Addition
print(f"x*2: {x*2}")       # Multiplication
print(f"x/2: {x/2}")       # Division
print(f"x//2: {x//2}")     # Floor Division
print(f"-x: {-x}")         # Negation
print(f"x**3: {x**3}")     # Exponent
print(f"x%2: {x%2}")       # Modulus

x: [0 1 2 3]
x-5: [-5 -4 -3 -2]
x+5: [5 6 7 8]
x*2: [0 2 4 6]
x/2: [0.  0.5 1.  1.5]
x//2: [0 0 1 1]
-x: [ 0 -1 -2 -3]
x**3: [ 0  1  8 27]
x%2: [0 1 0 1]


In [12]:
# Absolute Value
x = np.array([-3, 4, 7, -2, -11])
print(np.absolute(x))

[ 3  4  7  2 11]


# Trigonometric Functions

In [14]:
theta = np.linspace(0, np.pi, 3)
print(theta)
print(f"Sin Theta: {np.sin(theta)}")        # SIn theta
print(f"Cos Theta: {np.cos(theta)}")        # Cos Theta
print(f"Tan Theta: {np.tan(theta)}")        # Tan theta

# Inverse Trig functions --> arcsin, arccos, arctan

[0.         1.57079633 3.14159265]
Sin Theta: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cos Theta: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tan Theta: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


## Exponents and Logarithms

In [20]:
x = [1, 2, 3]
print(f"x: {x}")
print(f"e^x: {np.exp(x)}")
print(f"2^x: {np.exp2(x)}")
print(f"3^x: {np.power(x, 3)}")
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

x: [1, 2, 3]
e^x: [ 2.71828183  7.3890561  20.08553692]
2^x: [2. 4. 8.]
3^x: [ 1  8 27]
ln(x) = [0.         0.69314718 1.09861229]
log2(x) = [0.        1.        1.5849625]
log10(x) = [0.         0.30103    0.47712125]
exp(x) - 1 = [ 1.71828183  6.3890561  19.08553692]
log(1 + x) = [0.69314718 1.09861229 1.38629436]
